name = "kncursos"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
NODE_VERSION = "18"

[[d1_databases]]
binding = "DB"
database_name = "kncursos"
database_id = "6783bc59-1fd5-48b4-894b-98c77e6ca75a"

[[r2_buckets]]
binding = "R2"
bucket_name = "kncursos-pdfs"
